apiVersion: apps/v1
kind: Deployment
metadata:
  name: portfolio-dev
  namespace: portfolio-dev
  labels:
    app: portfolio-dev
spec:
  replicas: 1
  selector:
    matchLabels:
      app: portfolio-dev
  template:
    metadata:
      labels:
        app: portfolio-dev
    spec:
      containers:
        - name: portfolio-dev
          image: ghcr.io/naffsisky/portfolio:latest  # ganti ini
          ports:
            - containerPort: 3000
          env:
            - name: NODE_ENV
              value: "development"
            - name: PORT
              value: "3000"
            - name: HOSTNAME
              value: "0.0.0.0"
          resources:
            requests:
              memory: "256Mi"
              cpu: "100m"
            limits:
              memory: "512Mi"
              cpu: "500m"
          readinessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 10
            periodSeconds: 10
          livenessProbe:
            httpGet:
              path: /
              port: 3000
            initialDelaySeconds: 30
            periodSeconds: 30