apiVersion: v1
kind: Service
metadata:
  name: portfolio-dev-svc
  namespace: portfolio-dev
spec:
  type: NodePort
  selector:
    app: portfolio-dev
  ports:
    - protocol: TCP
      port: 80
      targetPort: 3000
      nodePort: 30080